// Mock data for the application
export const mockRestaurants = [
  {
    id: 1,
    name: "カフェ・ド・パリ",
    genre: "フレンチ",
    distance: 0.2,
    available_seats: 3,
    rating: 4.5,
    price_range: "¥2,000-3,000",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: true,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都渋谷区渋谷1-2-3 渋谷ビル2F",
    phone: "03-1234-5678",
    hours: "11:00-22:00",
    closedDays: "火曜日",
    crowdLevel: "普通",
    reviewCount: 128,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    description: "本格的なフレンチ料理を気軽に楽しめるカフェです。",
  },
  {
    id: 2,
    name: "寿司 銀座",
    genre: "和食",
    distance: 0.5,
    available_seats: 2,
    rating: 4.8,
    price_range: "¥5,000-8,000",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: false,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都中央区銀座1-2-3",
    phone: "03-2345-6789",
    hours: "17:00-23:00",
    closedDays: "日曜日",
    crowdLevel: "混雑",
    reviewCount: 256,
    images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    description: "新鮮な魚介を使った本格江戸前寿司をお楽しみください。",
  },
  {
    id: 3,
    name: "イタリアン・ビストロ",
    genre: "イタリアン",
    distance: 0.8,
    available_seats: 5,
    rating: 4.3,
    price_range: "¥3,000-4,000",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: true,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都新宿区新宿1-2-3",
    phone: "03-3456-7890",
    hours: "12:00-21:00",
    closedDays: "月曜日",
    crowdLevel: "空いている",
    reviewCount: 89,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    description: "本場イタリアの味を再現したアットホームなビストロです。",
  },
  {
    id: 4,
    name: "焼肉 炭火亭",
    genre: "焼肉",
    distance: 0.3,
    available_seats: 4,
    rating: 4.6,
    price_range: "¥3,000-4,000",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: true,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都渋谷区渋谷2-3-4",
    phone: "03-4567-8901",
    hours: "17:00-24:00",
    closedDays: "水曜日",
    crowdLevel: "普通",
    reviewCount: 167,
    images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    description: "炭火で焼く上質なお肉をリーズナブルな価格で提供しています。",
  },
  {
    id: 5,
    name: "パスタ・ハウス",
    genre: "イタリアン",
    distance: 0.7,
    available_seats: 2,
    rating: 4.2,
    price_range: "¥2,000-3,000",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: false,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都港区六本木1-2-3",
    phone: "03-5678-9012",
    hours: "11:30-22:00",
    closedDays: "木曜日",
    crowdLevel: "普通",
    reviewCount: 94,
    images: ["/placeholder.svg?height=300&width=400"],
    description: "手打ちパスタが自慢のカジュアルイタリアンレストランです。",
  },
  {
    id: 6,
    name: "天ぷら 季節",
    genre: "和食",
    distance: 1.2,
    available_seats: 1,
    rating: 4.7,
    price_range: "¥4,000-6,000",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: true,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都千代田区丸の内1-2-3",
    phone: "03-6789-0123",
    hours: "17:30-22:30",
    closedDays: "日曜日",
    crowdLevel: "空いている",
    reviewCount: 203,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    description: "季節の食材を使った上品な天ぷらをお楽しみいただけます。",
  },
  {
    id: 7,
    name: "炭火焼き鳥 とり源",
    genre: "焼肉",
    distance: 0.3,
    available_seats: 3,
    rating: 4.6,
    price_range: "¥2,500-3,500",
    image_url: "/placeholder.svg?height=120&width=120",
    subscription_discount: true,
    available_now: true,
    created_at: new Date().toISOString(),
    address: "東京都渋谷区渋谷1-2-3 渋谷ビル2F",
    phone: "03-1234-5678",
    hours: "17:00-24:00（L.O.23:30）",
    closedDays: "日曜日",
    crowdLevel: "普通",
    reviewCount: 128,
    images: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    description:
      "炭火で丁寧に焼き上げる絶品焼き鳥が自慢の居酒屋です。新鮮な国産鶏を使用し、秘伝のタレで味付けした焼き鳥は絶品です。",
  },
]

export const mockReservations = [
  {
    id: 1,
    restaurantName: "カフェ・ド・パリ",
    date: "2024年1月15日",
    time: "19:00",
    people: 2,
    status: "仮押さえ中",
    expiresIn: "15分",
    image: "/placeholder.svg?height=60&width=80",
  },
  {
    id: 2,
    restaurantName: "焼肉 炭火亭",
    date: "2024年1月18日",
    time: "18:30",
    people: 4,
    status: "仮押さえ中",
    expiresIn: "8分",
    image: "/placeholder.svg?height=60&width=80",
  },
  {
    id: 3,
    restaurantName: "寿司 銀座",
    date: "2024年1月20日",
    time: "18:30",
    people: 4,
    status: "予約確定",
    image: "/placeholder.svg?height=60&width=80",
  },
  {
    id: 4,
    restaurantName: "パスタ・ハウス",
    date: "2023年12月28日",
    time: "20:00",
    people: 2,
    status: "来店済み",
    image: "/placeholder.svg?height=60&width=80",
  },
  {
    id: 5,
    restaurantName: "天ぷら 季節",
    date: "2023年12月20日",
    time: "19:30",
    people: 3,
    status: "キャンセル済み",
    image: "/placeholder.svg?height=60&width=80",
  },
]

export const mockComments = [
  {
    id: 1,
    restaurantName: "カフェ・ド・パリ",
    visitDate: "2024年1月10日",
    userComment: "雰囲気が良く、料理も美味しかったです。特にデザートが絶品でした！",
    restaurantReply:
      "ご来店ありがとうございました！デザートを気に入っていただけて嬉しいです。またのお越しをお待ちしております。",
    reactions: [
      { type: "heart", count: 3 },
      { type: "thumbsup", count: 1 },
    ],
    image: "/placeholder.svg?height=60&width=80",
    rating: 4.5,
    replied: true,
  },
  {
    id: 2,
    restaurantName: "焼肉 炭火亭",
    visitDate: "2024年1月5日",
    userComment: "お肉の質が素晴らしく、サービスも丁寧でした。",
    restaurantReply: null,
    reactions: [{ type: "heart", count: 2 }],
    image: "/placeholder.svg?height=60&width=80",
    rating: 4.8,
    replied: false,
  },
]

export const mockNotifications = [
  {
    id: 1,
    type: "reservation",
    title: "予約確認のお知らせ",
    message: "寿司 銀座での予約が確定しました。1月20日 18:30〜",
    time: "2時間前",
    read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    type: "promotion",
    title: "会員限定特典",
    message: "今週末限定！対象店舗で20%オフクーポンをプレゼント",
    time: "1日前",
    read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    type: "alert",
    title: "仮押さえ期限のお知らせ",
    message: "カフェ・ド・パリの仮押さえがあと15分で期限切れになります",
    time: "2日前",
    read: true,
    created_at: new Date().toISOString(),
  },
]

export const mockUserProfile = {
  id: "mock-user-id",
  name: "田中太郎",
  subscription_plan: "premium",
  subscription_expires_at: "2024-12-31T23:59:59Z",
  created_at: new Date().toISOString(),
}

export const mockUserStats = {
  totalApplications: 24,
  averageRating: 4.6,
  totalReviews: 12,
}

// Helper functions
export function getRestaurantById(id: number) {
  return mockRestaurants.find((r) => r.id === id) || mockRestaurants[0]
}

export function getCrowdLevel(restaurant: any) {
  if (restaurant.available_seats > 3) return "空いている"
  if (restaurant.available_seats > 1) return "普通"
  return "混雑"
}
